### ISSUE TITLE
Installing VS Code on Mac: broken verification link

### ISSUE THREAD

**Issue by lexischubert** [pp4rs/2021-uzh-installation-guide#1]
Nothin major, but I thought I'd mention that the "below" link is broken 
<img width="632" alt="Screen Shot 2021-08-12 at 6 13 36 PM" src="https://user-images.githubusercontent.com/60316653/129231244-166dbbfb-470c-4f96-bb41-190b483fae57.png">

**Comment by lachlandeer** [comment]
thanks, fixed with 537679a2f63dc9ecff8c3267f6ed2087e7f1a8df
