### ISSUE TITLE
Python installation

### ISSUE THREAD

**Issue by lexischubert** [pp4rs/2021-uzh-installation-guide#3]
The installation command should be updated to: 
`brew install --cask anaconda`

**Comment by lexischubert** [comment]
`source .bash_profile` gives the same error message as before: 
<img width="561" alt="Screen Shot 2021-08-12 at 6 26 28 PM" src="https://user-images.githubusercontent.com/60316653/129233043-c4307f8e-b274-4ac4-85e8-97c00f599620.png">

**Comment by lexischubert** [comment]
(FYI: It seems like python 2 was already installed on the laptop that the IT gave me and I guess that's why you have the note at the bottom)

**Comment by lexischubert** [comment]
<img width="882" alt="Screen Shot 2021-08-12 at 6 30 39 PM" src="https://user-images.githubusercontent.com/60316653/129233702-52bbd280-7129-4fc4-9ffa-a976f8efd440.png">

It doesn't recognize either of the pip update commands

**Comment by lexischubert** [comment]
<img width="964" alt="Screen Shot 2021-08-12 at 6 36 15 PM" src="https://user-images.githubusercontent.com/60316653/129234425-da0740f2-8899-4aab-a6a4-e176f437b108.png">
Sad circular world...

**Comment by lachlandeer** [comment]
try replacing pip with pip3 everywhere

the python 2 install (which I think macs are using under the hood might be the problem)

**Comment by lachlandeer** [comment]
brew's cask install fix is now in 27416a25ac43cc8a453b80bcab5956230d0de186

this makes anaconda available from command line bb27c6352b95fc7328183855a405df1cdd010238

**Comment by lexischubert** [comment]
<img width="935" alt="Screen Shot 2021-08-13 at 2 09 58 PM" src="https://user-images.githubusercontent.com/60316653/129355076-847e2e5f-93a6-4b1c-858d-4ab264ba7bc2.png">


At first I circled through all the different pip3 possibilities and it didn't work:
`pip3 install --upgrade pip3`
`python3 -m pip3 install --upgrade pip3`
`python3 -m pip3 install --upgrade pip `
`python3 -m pip install --upgrade pip `

But I just realized that it must be an admin issue because once I added user it worked `python3 -m pip install --upgrade pip  --user`

**Comment by lexischubert** [comment]
<img width="934" alt="Screen Shot 2021-08-13 at 2 12 28 PM" src="https://user-images.githubusercontent.com/60316653/129355374-1910cb76-cb99-4e9b-b3c4-9e6d6b8f0794.png">

Not sure if these warnings mean anything, but they popped up with "linearmodels" and "virtualenvwrapper"

**Comment by lachlandeer** [comment]
I think we have these under control now, so I'll close.

Open a new issue if we get more problems as students go through the guide
