### ISSUE TITLE
Webscraping

### ISSUE THREAD

**Issue by lexischubert** [pp4rs/2021-uzh-installation-guide#4]
as before: ` brew install --cask google-chrome`

**Comment by lexischubert** [comment]
<img width="574" alt="Screen Shot 2021-08-13 at 2 27 27 PM" src="https://user-images.githubusercontent.com/60316653/129356959-aab52ca6-f2d6-4887-9d81-e222d5b8fca1.png">


Any thoughts on what to do when chrome is already installed? Linking/ upgrading/ checking the version didn't work.
(Dumb question: if I were to uninstall it, would all my chrome settings be lost?)

**Comment by lexischubert** [comment]
<img width="812" alt="Screen Shot 2021-08-13 at 2 30 26 PM" src="https://user-images.githubusercontent.com/60316653/129357384-c2e45b3e-e067-4d39-871b-f7797d236d54.png">

But it works once you go to System Preferences > Security & Privacy > Allow apps downloaded from > "Always allow" next to chromedriver

**Comment by lachlandeer** [comment]
Fixed with 87596b0

Open a new issue of persists
