### ISSUE TITLE
Snakemake version

### ISSUE THREAD

**Issue by lexischubert** [pp4rs/2021-uzh-installation-guide#5]
<img width="567" alt="Screen Shot 2021-08-13 at 2 37 13 PM" src="https://user-images.githubusercontent.com/60316653/129358114-cc07246d-8a49-47aa-ab7a-03b49eb4252c.png">

I successfully installed snakemake but it doesn't like to tell me the version with `snakemake --version`. At first I thought it might be a zsh issue, but it worked fine with `chromedriver --version`

**Comment by lachlandeer** [comment]
Left a note of this on the page with 87596b0
